/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import dao.EtudiantDAO;
import model.Etudiant;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
import dao.NoteDAO;
import javax.swing.table.TableRowSorter;
import javax.swing.RowFilter;

/**
 *
 * @author hamza
 */
public class FormEtudiant extends javax.swing.JFrame {
private String role;
private TableRowSorter<DefaultTableModel> sorter;




    /**
     * Creates new form FormEtudiant
     */
DefaultTableModel model;

public FormEtudiant() {
    initComponents();
    this.setLocationRelativeTo(null); // يجي فالنص
    this.getContentPane().setBackground(new java.awt.Color(245, 247, 250));
    styleButton(jButton2, new java.awt.Color(40, 167, 69)); // Ajouter
    styleButton(btnModifier, new java.awt.Color(0, 123, 255)); // Modifier
    styleButton(btnSupprimer, new java.awt.Color(220, 53, 69)); // Supprimer
    styleButton(btnLogout, new java.awt.Color(108, 117, 125)); // Logout
    
    
    styleTextField(txtnom);
    styleTextField(txtprenom);
    styleMoyenne(txtMoyenne);


    DefaultTableModel model = (DefaultTableModel) tableEtudiant.getModel();
    sorter = new TableRowSorter<>(model);
    tableEtudiant.setRowSorter(sorter);

    chargerEtudiants();
}
public FormEtudiant(String role) {
    this.role = role;
    initComponents();
    chargerEtudiants();
     appliquerPermissions();
    this.setLocationRelativeTo(null);
    this.getContentPane().setBackground(new java.awt.Color(245, 247, 250));

   
}
private void appliquerPermissions() {
    if ("USER".equals(role)) {
        jButton2.setEnabled(false);   // Ajouter
        btnModifier.setEnabled(false);
        btnSupprimer.setEnabled(false);
    }
}

private void styleButton(javax.swing.JButton btn, java.awt.Color bg) {
        btn.setBackground(bg);
        btn.setForeground(java.awt.Color.WHITE);
        btn.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
        btn.setFocusPainted(false);
        btn.setBorderPainted(false);
    }
private void styleTextField(javax.swing.JTextField txt) {
    txt.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14));
    txt.setBackground(java.awt.Color.WHITE);
    txt.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(5, 8, 5, 8)
        )
    );
}
private void styleMoyenne(javax.swing.JLabel lbl) {
    lbl.setOpaque(true);
    lbl.setBackground(new java.awt.Color(233, 236, 239)); // gris clair
    lbl.setForeground(new java.awt.Color(33, 37, 41));   // dark
    lbl.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 16));
    lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    lbl.setBorder(
        javax.swing.BorderFactory.createCompoundBorder(
            javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)),
            javax.swing.BorderFactory.createEmptyBorder(8, 10, 8, 10)
        )
    );
}

private void chargerEtudiants() {
    if (tableEtudiant == null) {
        return;
    }

    DefaultTableModel model = (DefaultTableModel) tableEtudiant.getModel();
    model.setRowCount(0);

    EtudiantDAO dao = new EtudiantDAO();
    List<Etudiant> list = dao.getAllEtudiants();

    if (list == null) return;

    for (Etudiant e : list) {
        model.addRow(new Object[]{
            e.getId(),
            e.getNom(),
            e.getPrenom()
        });
    }
    sorter = new TableRowSorter<>((DefaultTableModel) tableEtudiant.getModel());
tableEtudiant.setRowSorter(sorter);

}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jFrame1 = new javax.swing.JFrame();
        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnom = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtprenom = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEtudiant = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        btnModifier = new javax.swing.JButton();
        btnSupprimer = new javax.swing.JButton();
        btnNouveau = new javax.swing.JButton();
        txtMoyenne = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        jToggleButton1.setText("jToggleButton1");

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Suivi les Notes");
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(153, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        setForeground(new java.awt.Color(0, 255, 51));
        setPreferredSize(new java.awt.Dimension(750, 485));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jLabel1.setBackground(new java.awt.Color(255, 51, 51));
        jLabel1.setForeground(new java.awt.Color(51, 0, 51));
        jLabel1.setText("Nom");

        txtnom.setBackground(new java.awt.Color(204, 255, 255));
        txtnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 51, 51));
        jLabel2.setForeground(new java.awt.Color(51, 0, 51));
        jLabel2.setText("Prenom");

        jButton1.setBackground(new java.awt.Color(204, 204, 255));
        jButton1.setText("Afficher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtprenom.setBackground(new java.awt.Color(204, 255, 255));
        txtprenom.setText("\n");
        txtprenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtprenomActionPerformed(evt);
            }
        });

        tableEtudiant.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, new java.awt.Color(0, 255, 204), java.awt.Color.darkGray, java.awt.Color.gray));
        tableEtudiant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEtudiant.setToolTipText("Liste des Étudiants");
        tableEtudiant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEtudiantMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEtudiant);

        jButton2.setBackground(new java.awt.Color(0, 102, 255));
        jButton2.setFont(new java.awt.Font("Bell MT", 0, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Ajouter");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnModifier.setText("Modifier");
        btnModifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifierActionPerformed(evt);
            }
        });

        btnSupprimer.setText("Supprimer");
        btnSupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupprimerActionPerformed(evt);
            }
        });

        btnNouveau.setText("Nouveau");
        btnNouveau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNouveauActionPerformed(evt);
            }
        });

        txtMoyenne.setBackground(new java.awt.Color(153, 255, 255));
        txtMoyenne.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMoyenne.setForeground(new java.awt.Color(51, 0, 51));
        txtMoyenne.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtMoyenne.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(153, 255, 255), new java.awt.Color(153, 255, 255), new java.awt.Color(102, 255, 255), new java.awt.Color(102, 255, 255)));

        jLabel3.setText("Moyenne");

        btnLogout.setBackground(new java.awt.Color(51, 255, 204));
        btnLogout.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton2)
                                .addGap(14, 14, 14)
                                .addComponent(btnModifier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSupprimer)
                                .addGap(10, 10, 10)
                                .addComponent(btnNouveau))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1)))
                            .addComponent(btnLogout)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtMoyenne, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtnom, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtprenom, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))))
                .addContainerGap(101, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtMoyenne, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(78, 78, 78))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2)
                            .addComponent(btnModifier)
                            .addComponent(btnSupprimer)
                            .addComponent(btnNouveau))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btnLogout)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

 
EtudiantDAO dao = new EtudiantDAO();
List<Etudiant> list = dao.getAllEtudiants();

DefaultTableModel model = new DefaultTableModel();
model.addColumn("ID");
model.addColumn("Nom");
model.addColumn("Prenom");

for (Etudiant e : list) {
    model.addRow(new Object[]{
        e.getId(),
        e.getNom(),
        e.getPrenom()
    });
}

tableEtudiant.setModel(model);

    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtnomActionPerformed

    private void txtprenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtprenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtprenomActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO 
        // جلب النص من الحقول
String nom = txtnom.getText();
String prenom = txtprenom.getText();

// التحقق من الحقول
if (nom.isEmpty() || prenom.isEmpty()) {
    JOptionPane.showMessageDialog(this, "Remplir tous les champs !");
    return;
}

// إنشاء كائن Etudiant
Etudiant e = new Etudiant();
e.setNom(nom);
e.setPrenom(prenom);

// إضافة للقاعدة
EtudiantDAO dao = new EtudiantDAO();
dao.ajouterEtudiant(e);

// رسالة نجاح
JOptionPane.showMessageDialog(this, "Etudiant ajouté ✅");

// تفريغ الحقول
txtnom.setText("");
txtprenom.setText("");

// تحديث الجدول تلقائياً
List<Etudiant> list = dao.getAllEtudiants();

DefaultTableModel model = new DefaultTableModel();
model.addColumn("ID");
model.addColumn("Nom");
model.addColumn("Prenom");

for (Etudiant etud : list) {
    model.addRow(new Object[]{
        etud.getId(),
        etud.getNom(),
        etud.getPrenom()
    });
}

tableEtudiant.setModel(model);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableEtudiantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEtudiantMouseClicked

    int row = tableEtudiant.getSelectedRow();

  if (row != -1) {
        try {
            // Get ID
            int id = Integer.parseInt(tableEtudiant.getValueAt(row, 0).toString());
            
            // Afficher Nom o Prenom
            txtnom.setText(tableEtudiant.getValueAt(row, 1).toString());
            txtprenom.setText(tableEtudiant.getValueAt(row, 2).toString());
            
            // Calcul Moyenne - JDID!
            NoteDAO noteDAO = new NoteDAO();
            double moyenne = noteDAO.calculerMoyenne(id);
            txtMoyenne.setText(String.format("%.2f", moyenne));
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
        }
    }

    }//GEN-LAST:event_tableEtudiantMouseClicked

    private void btnNouveauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNouveauActionPerformed
 txtnom.setText("");
    txtprenom.setText("");
    tableEtudiant.clearSelection();
            int row = tableEtudiant.getSelectedRow();
            if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un étudiant!");
        return;
    }
           try {
        int id = Integer.parseInt(tableEtudiant.getValueAt(row, 0).toString());
        String nom = txtnom.getText().trim();
        String prenom = txtprenom.getText().trim();
        
        if (nom.isEmpty() || prenom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Remplissez tous les champs!");
            return;
        }
        
        Etudiant e = new Etudiant();
        e.setId(id);
        e.setNom(nom);
        e.setPrenom(prenom);
        
        EtudiantDAO dao = new EtudiantDAO();
        dao.modifier(e);
        
        chargerEtudiants(); // Refresh table
        JOptionPane.showMessageDialog(this, "Modifié avec succès!");
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
    }

    }//GEN-LAST:event_btnNouveauActionPerformed

    private void btnModifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifierActionPerformed
       // TODO add your handling code here:
            int row = tableEtudiant.getSelectedRow();
if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un étudiant!");
        return;
    }
 try {
        int id = Integer.parseInt(tableEtudiant.getValueAt(row, 0).toString());
        String nom = txtnom.getText().trim();
        String prenom = txtprenom.getText().trim();
        
        if (nom.isEmpty() || prenom.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Remplissez tous les champs!");
            return;
        }
Etudiant e = new Etudiant();
        e.setId(id);
        e.setNom(nom);
        e.setPrenom(prenom);
        
        EtudiantDAO dao = new EtudiantDAO();
        dao.modifier(e);
        
        chargerEtudiants();
        JOptionPane.showMessageDialog(this, "Modifié avec succès!");
        
    } catch (Exception ex) {
        JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
    }
    }//GEN-LAST:event_btnModifierActionPerformed

    private void btnSupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupprimerActionPerformed
 int row = tableEtudiant.getSelectedRow();
if (row == -1) {
        JOptionPane.showMessageDialog(this, "Sélectionnez un étudiant!");
        return;
    }
    
    int confirm = JOptionPane.showConfirmDialog(
        this, 
        "Voulez-vous vraiment supprimer?", 
        "Confirmation", 
        JOptionPane.YES_NO_OPTION
    );
    
    if (confirm == JOptionPane.YES_OPTION) {
        try {
            int id = Integer.parseInt(tableEtudiant.getValueAt(row, 0).toString());
            
            EtudiantDAO dao = new EtudiantDAO();
            dao.supprimer(id);
            
            chargerEtudiants();
            txtnom.setText("");
            txtprenom.setText("");
            
            JOptionPane.showMessageDialog(this, "Supprimé avec succès!");
            
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erreur: " + ex.getMessage());
        }
    }
    }//GEN-LAST:event_btnSupprimerActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
 int confirm = JOptionPane.showConfirmDialog(
        this,
        "Voulez-vous vraiment se déconnecter ?",
        "Logout",
        JOptionPane.YES_NO_OPTION
    );

    if (confirm == JOptionPane.YES_OPTION) {
        new LoginForm().setVisible(true);
        this.dispose();
    }
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
 try {
   com.formdev.flatlaf.FlatLightLaf.setup();
    } catch (Exception ex) {
        ex.printStackTrace();
    }

      java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
new LoginForm().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnModifier;
    private javax.swing.JButton btnNouveau;
    private javax.swing.JButton btnSupprimer;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tableEtudiant;
    private javax.swing.JLabel txtMoyenne;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    // End of variables declaration//GEN-END:variables
}
